name: My first workflow

on: push

jobs:
    first_job: 
      runs-on: ubuntu-latest
      steps: 
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: Welcome message
          run: echo "Hello My first Github Actions"
        
        - name: List files
          run: ls

        - name: Read File
          run: cat README.md