name: My First Workflow
on: [push] 
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Muti line commands
        run: |
          echo "This is a multi-line command"
          ls -la
          cat README.md
      - name: Install cowsay
        run: sudo apt-get install -y cowsay

      - name: generate ascii art work
        run: cowsay -f dragon "Hello, World!" >> dragon.txt

      - name: Read ascii art
        run: cat dragon.txt
        

