name: My Second Workflow
on: push
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "Welcome to my first GitHub Actions workflow!"

      # - name: List Files
      #   run: ls

      # - name: Read Files
      #   run: cat README.md
